main:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 1
  - identifier: "archives"
    name: "Archives"
    url: "/archives"
    weight: 2
  - identifier: "tags"
    name: "Tags"
    url: "/tags"
    weight: 3
